services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: bino
      POSTGRES_PASSWORD: ${BINO_DB_PASSWORD}
      POSTGRES_DB: bino
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5051:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      # NOTE: if these are changed run `docker rm bino-pgadmin-1` to refresh
      PGADMIN_DEFAULT_EMAIL: name@example.com
      PGADMIN_DEFAULT_PASSWORD: ${BINO_DB_PASSWORD}
      PGADMIN_SERVER_JSON_FILE: /pgadmin/servers.json
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
       - pgadmin:/root/.pgadmin
  bino:
    build: .
    depends_on:
      - db
    environment:
      BINO_DB_PASSWORD: ${BINO_DB_PASSWORD}
      BINO_DB_HOST: db
      BINO_DB_PORT: 5432
    ports:
      - "8080:8080"
    volumes:
      - ./config.json:/config.json
      - ./secret:/secret

volumes:
  pgdata:
  pgadmin:
  